# Generated by Django 3.1.4 on 2021-06-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210611_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_mode', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], max_length=50)),
                ('message', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('scheduled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.college')),
                ('counselling_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counselling.counselling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_mode', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], max_length=100)),
                ('message', models.TextField(null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselor_schedule', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselling.request')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
