# Generated by Django 3.1.4 on 2021-06-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='message',
        ),
    ]
