# Generated by Django 3.1.4 on 2021-06-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0002_remove_schedule_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
