# Generated by Django 3.1.4 on 2021-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0003_schedule_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
