# Generated by Django 3.1.4 on 2021-06-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0007_auto_20210613_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('date',)},
        ),
    ]
