# Generated by Django 3.1.4 on 2021-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0008_auto_20210614_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
