# Generated by Django 3.1.4 on 2021-06-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='college_logo/')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='hall_of_affiliation',
            field=models.CharField(choices=[('Unity Hall', 'Unity Hall')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellor',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counsellers', to='accounts.college'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.College'),
        ),
    ]
