# Generated by Django 3.1.4 on 2021-06-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210611_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_of_affiliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.hall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.programme'),
            preserve_default=False,
        ),
    ]
