# Generated by Django 3.1.4 on 2021-06-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210616_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_nuumber',
            new_name='phone_number',
        ),
    ]
