# Generated by Django 3.1.4 on 2021-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210616_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='index_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
